package com.pacman.screens;

public enum WallAtlasRegion {
    EMPTY, // 0
    INNER_WALL_HORIZONTAL_BOTTOM_SIDE, // 1
    INNER_WALL_HORIZONTAL_TOP_SIDE, // 2
    INNER_WALL_VERTICAL_LEFT_SIDE, // 3
    INNER_WALL_VERTICAL_RIGHT_SIDE, // 4
    INTERSECTION_BOTTOM_END_LEFT, // 5
    INTERSECTION_BOTTOM_END_RIGHT, // 6
    INTERSECTION_LEFT_END_BOTTOM, // 7
    INTERSECTION_LEFT_END_TOP, // 8
    INTERSECTION_RIGHT_END_BOTTOM, // 9
    INTERSECTION_RIGHT_END_TOP, // 10
    INTERSECTION_TOP_END_LEFT, // 11
    INTERSECTION_TOP_END_RIGHT, // 12
    JAIL_BOTTOM_LEFT_CORNER, // 13
    JAIL_BOTTOM_RIGHT_CORNER, // 14
    JAIL_DOOR, // 15
    JAIL_TOP_LEFT_CORNER, // 16
    JAIL_TOP_RIGHT_CORNER, // 17
    OUTER_WALL_BOTTOM_LEFT_CORNER, // 18
    OUTER_WALL_BOTTOM_RIGHT_CORNER, // 19
    OUTER_WALL_HORIZONTAL_BOTTOM, // 20
    OUTER_WALL_HORIZONTAL_TOP, // 21
    OUTER_WALL_TOP_LEFT_CORNER, // 22
    OUTER_WALL_TOP_RIGHT_CORNER, // 23
    OUTER_WALL_VERTICAL_LEFT, // 24
    OUTER_WALL_VERTICAL_RIGHT, // 25
    PELLET_LARGE, // 26
    PELLET_SMALL, // 27
    T_SHAPE_HORIZONTAL_BASE_DOWN_INTERSECTION_LEFT_SIDE, // 28
    T_SHAPE_HORIZONTAL_BASE_DOWN_INTERSECTION_RIGHT_SIDE, // 29
    T_SHAPE_HORIZONTAL_BASE_UP_INTERSECTION_LEFT_SIDE, // 30
    T_SHAPE_HORIZONTAL_BASE_UP_INTERSECTION_RIGHT_SIDE, // 31
    T_SHAPE_VERTICAL_BASE_LEFT_INTERSECTION_BOTTOM_SIDE, // 32
    T_SHAPE_VERTICAL_BASE_LEFT_INTERSECTION_TOP_SIDE, // 33
    T_SHAPE_VERTICAL_BASE_RIGHT_INTERSECTION_BOTTOM_SIDE, // 34
    T_SHAPE_VERTICAL_BASE_RIGHT_INTERSECTION_TOP_SIDE, // 35
    WALL_SQUARE_BOTTOM_LEFT_CORNER, // 36
    WALL_SQUARE_BOTTOM_RIGHT_CORNER, // 37
    WALL_SQUARE_TOP_LEFT_CORNER, // 38
    WALL_SQUARE_TOP_RIGHT_CORNER // 39
}
